### ISSUE TITLE
Border color

### ISSUE THREAD

**Issue by guillaumervls** [jxnblk/styled-system#133]
Hi and thanks for the module,

It seems (latest Chrome) that defining `border: 1px solid` implies `border: 1px solid initial`, so if a class defining `border-color` has a name alphabetically before the `border` class, which happens in my case with [Fela](http://fela.js.org/), `border-color` is ignored.

Maybe it would be safer not to use `border` (and other) shorthand properties ?

Tell me if I missed something.

Cheers

**Comment by jxnblk** [comment]
Does fela not maintain source order of where you add the functions? If the functions are added with `borderColor` last, this should work as expected.

Otherwise, you can probably get around that for now by creating your own function using the `style` or `responsiveStyle` utilities

**Comment by JoshRosenstein** [comment]
@guillaumervls - why not define border color after?
Or you can do any of the following:

1. create a custom getter function
2. create your own non shorthand border styles.
3.  create shorthand border style that referencing a custom key in your theme like:


````
///Default Border Style
const getBorder = n => util.num(n) && n > 0 ? n + 'px solid' : n 

const border = responsiveStyle({ ///default
  prop: 'border',
  key: 'borders',
  getter: getBorder
})

///Custom Getter Function
const getBlueBorder= n => util.num(n) && n > 0 ? n + 'px solid #0000ff ' : n 

const borderCustom = responsiveStyle({ ///default
  prop: 'border',
  key: 'borders',
  getter: getBlueBorder
})

///Custom non Shorhand
import borderColor from 'styled-system'

const borderWidth= responsiveStyle({ 
  prop: 'borderWidth',
})

const borderStyle= style({ 
  prop: 'borderStyle',
})

const MyCustomBorderStyle=props=({
...borderColor (props),
  ...borderWidth(props),
  ...borderStyle(props),
})

///Custom Shorthand with different key

const getBorder = n => util.num(n) && n > 0 ? n + 'px solid' : n 

const border = responsiveStyle({ ///default
  prop: 'border',
  key: 'Customborders',
  getter: getBorder
})

//Where theme has
theme{Customborders:{borderoption1: '1 px solid', borderoption2: '1 px solid blue', ....}
...
````

**Comment by guillaumervls** [comment]
Thanks for your replies!

Yes I created a "custom" function.

@jxnblk it seems that you can't really control the order of the 1-letter class names generated by Fela. They actually talk about this in their doc [http://fela.js.org/docs/introduction/Caveats.html#2-shorthand--longhand-properties]()

**Comment by VinceSJ** [comment]
I think this issue should be reopened: the problem is not dependent on Fela and can be encountered using only styled-system.

If you have a component with a responsive border that also has a `borderColor`, every size other than the smallest one will ignore the given color and default to black due to how shorthand `border` properties work in CSS. For example:
```
border={['1px solid', '2px solid', '3px solid']}
borderColor="red"
```

You can see the example in action at [this codesandbox link](https://codesandbox.io/s/qx2jl4owx9).

This seems like a "gotcha" that's worth fixing to me because it's not obvious at first why the shorthand ignores your previously set border color. And while Josh's workaround above does the job, any workaround makes it harder to use the custom color theming (eg `gray.0`, etc.) someone using styled-system is probably using in other places.

**Comment by StevenLangbroek** [comment]
Ran into this and it took me a good 30 minutes to debug. The way it breaks is counterintuitive, and I think deserves maybe a fix on library level...

**Comment by chasemccoy** [comment]
@jxnblk This almost certainly deserves to be reopened. I can confirm that the Codesandbox that @VinceSJ posted above is the behavior I am seeing in our library/apps.

**Comment by ItsWendell** [comment]
Having same issues here

**Comment by ScottAgirs** [comment]
Same here, not related to any packages. The issue is also present using only styled-system.

```javascript
// theme
borders: [
    0,
    '1px solid',
    '2px solid',
  ],
```

Adding `borderColor` like so:

```javascript
// theme
 <Box borderColor="red" />
```

Will yield inherited border color (in this case) pink as seen here:

<img width="233" alt="Screen Shot 2021-01-16 at 8 40 55 PM" src="https://user-images.githubusercontent.com/11737572/104828816-2448d600-583b-11eb-8d36-8f09c15d4dfd.png">
