### ISSUE TITLE
Feature Request: Spacing Children

### ISSUE THREAD

**Issue by eugenkiss** [jxnblk/styled-system#139]
Occasionally, I want to have spacing between children. If I wrote:

```jsx
<Box>
  {xs.map(x => <Box mb={1}/>}
</Box>
```

I will have one pesky margin too much after the last child. To be correct, I need to write:

```jsx
<Box css=`
&>* {
  margin-top: ${v};
}
&>*:first-child {
  margin-top: 0;
}
`>
  {xs.map(x => <Box/>}
</Box>
```

See also the [“Spacing children” section](https://typestyle.github.io/#/box) of [TypeStyle](https://typestyle.github.io/) with the helpers `verticallySpaced` and `horizontallySpaced`.

In my project, I cobbled together these feature as follows:

```js
import styled from 'react-emotion'
import {css} from 'emotion'
import {util} from 'styled-system'

const vspace = props => {
  let v = props.vspace
  const theme = util.fallbackTheme(props)
  if (v == null) return undefined
  if (theme && theme.space && theme.space[v]) {
    v = util.px(theme.space[v])
  }
  return css`
    &>* {
      margin-top: ${v};
    }
    &>*:first-child {
      margin-top: 0;
    }
  `
}

export const Box = styled('div')`
${vspace}
…
` 
```

Now I can achieve proper spacing between children:

```jsx
<Box vspace={1}>
  {xs.map(x => <Box/>}
</Box>
```

With this issue I'd like to kick of a discussion whether `hspace`/`vspace` styles should be provided by styled-system. I for one would welcome them. Plus, at least another library, namely TypeStyle, provides them by default.

Secondarily, I was wondering about any pointers for improvements for my cobbled together `vspace` style.

**Comment by corygibbons** [comment]
Maybe not the most elegant but this has worked for me as a quick solution in the past:

```jsx
<Box>
  {xs.map((x, i) => <Box mb={i === xs.length - 1 ? 0 : 1} />}
</Box>
```

Untested but for your vspace util you _might_ be able to shorten it to something like this:
```jsx
import styled from 'react-emotion'
import {css} from 'emotion'
import {themeGet} from 'styled-system'

const vspace = props => {
  let v = props.vspace
  if (v == null) return undefined

  return css`
    &>* {
      margin-top: ${themeGet(`space[v]`)};
    }
    &>*:first-child {
      margin-top: 0;
    }
  `
}

export const Box = styled('div')`
  ${vspace};
   …
` 
```

**Comment by jxnblk** [comment]
FWIW, I generally try to avoid using `:nth-child` pseudo-classes since that can mostly be handled with JS. With CSS alone, you can compensate for child margins by using negative margins on the parent element as well.

I'm not 100% sure what you're proposing here, but it *did* remind me of something I meant to throw together, but never got around to. This uses styled-system's space props to style child elements without a wrapping parent container. https://github.com/jxnblk/grid-styled/tree/master/styled-space

Maybe that's helpful for what you're trying to achieve, but I'm not sure...

**Comment by selrond** [comment]
@eugenkiss @corygibbons @jxnblk The most elegant __CSS__ solution to this problem is a so-called "lobotomized owl selector":

`* + *` which selects (reading right to left) every element which has sibling element before itself.

This makes it easy to do something like this:

```css
.parent > * + * {
	margin-top: 10px;
}
```

Recommended reading: [Axiomatic CSS and Lobotomized Owls · An A List Apart Article](http://alistapart.com/article/axiomatic-css-and-lobotomized-owls)

**Comment by jxnblk** [comment]
Closing this since I think a few potential options have been discussed here
