### ISSUE TITLE
Inner ref not passed down when using `tag.input`

### ISSUE THREAD

**Issue by angusfretwell** [jxnblk/styled-system#180]
When using `tag.input` from `clean-tag`, inner refs are not being passed down to the input element. 

Using `tag` and setting `is="input"` on my component works fine.

**Comment by allforabit** [comment]
I am also experiencing this issue. It doesn't seem to be possible to use inner refs with components created using system components as these use `clean-tag` under the hood. This affects most of the components included with rebass as they use system components.

**Comment by allforabit** [comment]
I'm getting the following warning message when trying to use inner refs with components created with system components (e.g. with the `Select` component`):
"Stateless function components cannot be given refs. Attempts to access this ref will fail."
The reason I want to use innerRefs is to get access to the underlying dom as outlined here: https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md in the styled component docs.

In rebass the only components that work this way are the box and flex components because they are directly using styled components and not through the system components. Below is some sample code:
```
class Header extends React.Component {
  constructor(props){
    super(props);
    this.myRef = React.createRef();
  }
  
  componentDidMount() {
    console.log(this.myRef);
  }

  render() {
    return (
      <Banner
        color="white"
        ratio={2 / 3}
        bg="blue"
      >
        <Box >
          <Select innerRef={this.myRef}><option>Hi</option></Select>
      </Banner>
    );
  }
}

```

**Comment by jxnblk** [comment]
The latest versions of clean-tag and system-components use `React.fowardRef` which should resolve this issue. Please open a new issue if not
