### ISSUE TITLE
`blacklist` in system-components only works as first argument

### ISSUE THREAD

**Issue by vadistic** [jxnblk/styled-system#192]
When passing custom function to `system` (e.g. [like in the example in readme](https://github.com/jxnblk/styled-system/tree/master/system-components#using-custom-functions)), we usually need to blacklist prop to avoid passing them to underlying DOM element and avoid React errors.

There is handy `blacklist` option, but I noticed it's only working when it's passed as first argument.

**[CodeSandbox](https://codesandbox.io/s/mzx5rk8prj)** (Check out the console in dev tools)

```jsx
const Pass = system(
  {
    blacklist: ["customProp"]
  },
  "space",
  "fontSize",
  props => props.customProp && `font-weight: bold`
);

const Fail = system(
  "space",
  "fontSize",
  props => props.customProp && `font-weight: bold`,
  {
    blacklist: ["customProp"]
  }
);
```

I'm not sure whether it's not too much of an edge case, but letting you know 😄

**Comment by vadistic** [comment]
Also, I noticed that custom functions does not work as last argument.

```jsx
const ThisWorks = system(
  "space",
  "fontSize",
  "border",
  ({ color }) =>
    css`
      background-color: ${color};
    `,
  "layout"
);

const ThisDoesNot = system(
  "space",
  "fontSize",
  "border",
  "layout",
  ({ color }) =>
    css`
      background-color: ${color};
    `
);
```

Maybe I'm doing something silly somewhere (am I?), but I think it's another edge case.

I added example to linked CodeSandbox.

**Comment by jxnblk** [comment]
For the first issue, *only* the first argument can be `defaultProps` so your second example is behaving as expected. I.e. the API is `system(optionalDefaultProps, ...functionsOrKeys)`

As for the second comment, `layout` is not part of the styled-system API, so I believe that it's attempting to pass it in as a raw CSS string, creating `layoutbackground-color: hotpink;` instead of what you intend
