### ISSUE TITLE
Adding additional props to styled-system via theme?

### ISSUE THREAD

**Issue by mjsisley** [jxnblk/styled-system#23]
Hello, big fan of your work. Thanks for doing OSS!

In this library, you currently allow the usage of `responsiveStyles` to add additional props for use with the styled-system api. 

I am curious what you think about adding the ability to add props to styled-system through styled-components `ThemeProvider` that you wrap here.

So, if you wanted another attribute available on all components using `styled-system`... this could be added via the theme. 

```javascript
<ThemeProvider theme={{
    'styled-system-props': {
        'flex-direction': 'direction'
    }
}}>...</ThemeProvider>
```

If you wanted to go more complicated in the theme, you could allow distinguishing which props to add by component.

```javascript
<ThemeProvider theme={{
    'styled-system-props': {
          Flex: {
            'flex-direction': 'direction'
          }
    }
}}>...</ThemeProvider>
```

I think it may be nice to use the responsive api provided by `styled-system` w/o wrapping a bunch of Rebass (or other styled-system) components w/ `styled()` and adding `responsiveStyles` to them.

There may be a good reason not to do this... but if you think it makes sense, I'd be happy to work on a PR.

**Comment by jxnblk** [comment]
This is a pretty wild idea but I like it 😄 I'm guessing this would probably be another package built with styled-system though right?

**Comment by mjsisley** [comment]
I'll have to dig into the implementation, haven't had a chance yet. I was thinking it could fit as part of "configuring styled-system". But it also could probably fit within the Rebass layer. Or potentially as another separate package.

Basically it came to mind while using Rebass. Wasn't immediately clear how to extend the responsive api for other props. Trail lead to `styled-system`, which provides the `responsiveStyles` api to extend. Thought it may be nice to just add some desired props to the theme and have them available wherever the other `styled-system` props were available.

**Comment by AdamWagner** [comment]
I've also been thinking about how to do this. Subscribed.

**Comment by gragland** [comment]
I was looking to whether it would be possible to have the `removeProps()` utility function remove custom style props created with `style()` or `responsiveStyle()`. Doesn't seem possible without some kind of config system where these are all defined. I like the current simplicity, but wanted to throw that in as another reason a config system could make sense.

**Comment by MrArnoldPalmer** [comment]
@gragland that makes a lot of sense. We are building our own rebass like library of low level components and have modeled it after the toolchain that rebass uses. What we ended up doing was writing a couple of basic functions that are the basis for our styled-system

createResponsiveStyle & createStyleSystem

createResponsiveStyle works similarly to responsiveStyle but takes an optional third argument which is `formatter` that accepts props and can compute styles based on the theme or however really.

```
const fontSize = createResponsiveStyle("font-size", "f", (propVal, props) => {
  if (typeof propVal === "number") {
    return `${propVal}px`
  }
  // you can look up values on props.theme or wherever. This allows for passing any type to a style prop.
  ...
})
```

in our app, we wanted to merge the styles in the same breakpoints to prevent extra classes and style declarations. createStyleSystem takes an array of these functions and returns a function that accepts props and returns styles as configured.

```
const Text = styled.p`
  ${createStyleSystem([fontSizeSystem, spacingSystem])}
`
```

Both of these functions assume the convention of style props being a single value, or an array of mobile first ordered values.

@jxnblk I think a module like this could be something that styled-system is built on top of instead of the other way around. The "styled system" is just these conventions with some specific theme values and formatters already defined. I think this fits into the toolchain of higher + lower level modules that the user can choose how much abstraction to accept but can still opt in to conventions that they want.

rebass
grid-styled
styled-system
create-styled-system **

** or some other name.

**Comment by gragland** [comment]
@MrArnoldPalmer Nice! Would love to see something like your `createResponsiveStyle` function added to styled-components.

**Comment by mjsisley** [comment]
Also like that @MrArnoldPalmer.

Somewhat related to this issue: https://github.com/emotion-js/facepaint

**Comment by jxnblk** [comment]
Going to close this out since there hasn't been much discussion lately and other libraries are potentially more inline with the ideas here
