### ISSUE TITLE
Bug: system component's extending component won't apply blacklist option

### ISSUE THREAD

**Issue by youngboy** [jxnblk/styled-system#241]
for the case like in docs http://jxnblk.com/styled-system/system-components#extending-components

add blacklist option won't have any effect for rendered DOM, this will causing some React props warning in some cases..

ideally, I could just using emotion's `shouldForwardProp`, but seems I am not able to configure this since it is hard-coded https://github.com/jxnblk/styled-system/blob/master/system-components/src/emotion.js#L7

according to  https://github.com/jxnblk/styled-system/blob/master/system-components/src/System.js#L61, clean-tag is not apply when `is` prop is function.

for now I just added the following code to my project as a simple workaround...

```
import { omit } from 'clean-tag'

const cleanCmp = (Cmp) => {
  return ({blacklist, ...props}) => (
    <Cmp {...omit(props, blacklist)} />
  )
}

Link = system({
  is: cleanCmp(RouterLink),
  blacklist: [
    'is'
  ]
},
  // more ...
)

```

**Comment by frontendmonster** [comment]
Same here after upgrading to 2.3.6. 
It says: `Warning: Received a 'function' for a string attribute 'is'. If this is expected, cast the value to a string.`

and it passes all props to the dom (even blacklist).

```html
<svg class="sc-bZQynM bmMrtV" color="colors.secondary.light" blacklist="innerRef,css">
```

**Comment by youngboy** [comment]
The bug still exist in v3.0.2,

furthermore, in v3.0.2  user defined blacklist option won't merge with to builtin blacklist settings, see
https://github.com/jxnblk/styled-system/blob/master/system-components/src/System.js#L90

```
      Component.defaultProps = {
        ...baseProps,
        blacklist: [
          ...blacklist,
          ...(baseProps.blacklist || [])
        ],
        ...defaultProps // defaultProps.blacklist will override previous value
      }
```

**Comment by jxnblk** [comment]
I didn't intend for the `blacklist` prop in system-components to be part of the public API. This is an issue with the styled-components library, that should probably be resolved there. There is a long-running issue there to track progress: https://github.com/styled-components/styled-components/issues/439

If you want to use the blacklisting feature, I'd recommend using [clean-tag](https://github.com/jxnblk/styled-system/tree/master/clean-tag), as is mentioned in the docs. Even if the above PR is merged, I wouldn't recommend relying on the `blacklist` prop to work in system-components

**Comment by flybayer** [comment]
Yeah @jxnblk can you help us understand this a bit more?

I thought `system-components` used `clean-tag`, but just now looking at the source, it appears it doesn't? It seems `system-components` is using a custom blacklist feature which makes sense why you didn't intend for it to be part of the public API.

Is it a possibility to remove the custom blacklist feature and use `clean-tag` for `system-components` which would provide a solid `blacklist` prop?

I think we're having so many dom attribute warning problems with system-components because it uses strings to define the html element instead of the special styled-component tags (`styled.button`) which filters out non-dom attributes. Nothing is filtered when using strings.

As a result, using any additional props for conditional styling beyond what styled-system provides always results in a dom attribute warning where with plain styled-components, it wouldn't.

Alternatively, could we try to use the special styled-component tags if possible like this?
```js
const create = new System({
  createComponent: type => (...args) => styled(type)([], ...args)
})
```
changed to
```js
const create = new System({
  createComponent: type => (...args) => styled[type] ? styled[type]([], ...args) : styled(type)([], ...args)
})
```
