### ISSUE TITLE
Cannot use custom styling props when extending components created with clean-tag

### ISSUE THREAD

**Issue by yadielar** [jxnblk/styled-system#283]
Is this discouraged when using `styled-system` and `clean-tag`?

```js
import styled from 'react-emotion';
import { styles } from 'styled-system'
import tag from 'clean-tag';

// This component actually comes from a primitives folder (similar to Rebass)
const Box = styled(tag)`
    box-sizing: border-box;

    ${styles.width}
    ${styles.space}
    ${styles.fontSize}
    ${styles.color}
    ${styles.flex}
    ${styles.order}
    ${styles.alignSelf}
`;

const Dropzone = styled(Box)`
  cursor: ${props => props.isAllowed ? 'grabbing' : 'no-drop'};

  &:hover {
    background-color: ${props => props.isAllowed ? props.theme.gray : props.theme.lightRed};
  }
`;

const Page = (props) => {
  return <Dropzone p={2} mt={1} flex="1 1 auto" />
};
```

Using custom style props when extending components created with `clean-tag` results in the dreaded React warning: `Warning: React does not recognize 'isAllowed' prop on a DOM element.`

Because `Box` is using the `clean-tag` HOC, only the props used by `styled-system` are omitted, and we lose `styled()`'s own prop cleaning functionality.

Looking at the code for the new 3.0 version of Rebass it seems like [it no longer attempts to clean the HTML tags](https://github.com/rebassjs/rebass/blob/master/src/index.js) from styled-system attributes, and even [encourages extending](https://rebassjs.org/extending) using `styled()`. Though I'm not sure if the examples provided also encourage the use of additional custom style props (eg. [here](https://rebassjs.org/getting-started#extending)).

Is this an insurmountable issue of using `clean-tag`? I think it would be very helpful for all users of this library if a contributor could share some insights into the pros and cons of using `clean-tag` or even attempting to clean the outputted HTML nodes altogether.

PS. Thank you so much for all the efforts that have been put into sharing this library with the world. 😉

**Comment by jxnblk** [comment]
Thanks for the questions; I'll try to clarify some of the thinking.

The `clean-tag` package is intended solely for use with styled-system to remove unwanted style props from this library. Since this is React, it also exposes the `blacklist` prop so that you can use it in other cases, but you'll need to provide the entire array of prop names that you'll want to omit. Because it is a component, styled-components et al. won't attempt to remove non-HTML attribute props using their whitelists. The `clean-tag` component also provided an `is` prop to change the underlying element, which was used in Rebass. Since v4 of styled-components includes this prop (`as`) as a first-class citizen, the `is` prop functionality is no longer necessary.

I really think that both the `as` prop functionality and the ability to remove style props should be a responsibility of styled-components and not some user-land solution like `clean-tag`. And since the current whitelist approach in styled-components removes *most* of the styled-system style props, I decided to drop any of the hacks I was doing in that library. The amount of confusion and issues with `clean-tag` are evidence that this isn't a great solution for a library like Rebass.

That said, it's not that complex of a module, so if you want to use it for what it is, or fork it to suit your own use-cases, I'd say go ahead. If you weren't using `clean-tag` in your example above, you wouldn't see that warning, but you'd be inadvertantly rendering some SVG attributes on HTML elements in some cases, which shouldn't really cause any issues with the way browsers tend to handle things like that.

**Comment by yadielar** [comment]
Thank you so much for taking the time to share your thoughts! It's exactly what I was looking for since I know there aren't any clear-cut answers to these issues.

After reading various Github issues from this repo and looking at the source of other projects that use `styled-system` I was reaching the same conclusion as you: that the ability to remove style props should be a responsibility of styled-components. But I wanted to make sure I wasn't missing a subtle way of making `clean-tag` work ideally on all these scenarios.

You can go ahead and close this issue. Hopefully, others can still find it and benefit from the perspective you've shared.

Thanks again for all the hard work you've put into this library.
