### ISSUE TITLE
Problem with inheritance

### ISSUE THREAD

**Issue by tbranyen** [jxnblk/styled-system#345]
When I extend a base component that uses a styled-system function, I find that I'm unable to override this particular property in the way I'd expect. Find a unit test below that illustrates the problem. I would expect that a style property will always win no matter what as that is an explicit value provided by a consumer.

Any help is greatly appreciated:

``` javascript
it('will allow overriding extended component theme styles', () => {
  const Box = styled.div`${color}`;

  const theme = {
    colors: { red: '#F00' },
    Box: { color: 'red' },
    Flex: { color: 'blue' },
  };

  // Extend the Box
  const Flex = styled(Box)(themeGet('Flex'));

  const wrapper = mount(
    <Provider theme={theme}>
      <Flex color="green" />
    </Provider>
  ).find(Flex);

  const domNode = wrapper.getDOMNode();

  // Currently fails with: blue to equal green
  expect(getComputedStyle(domNode).color).toEqual('green');
});
```

Notes:

- If I remove the `color` css property fallback from the `Flex` block, the test passes
- If I add `color` function to after `themeGet('Flex')`, the test passes

Neither of these seem like idea solutions. I shouldn't have to add duplicate functions to sub-classed components. I also shouldn't be restricted from putting defaults into the theme.

**Comment by jxnblk** [comment]
This is due to how styled components (and CSS) works. In your example the Flex components styles will override the base Box styles (where the color function is added). You might be better off using default props for this example

**Comment by tbranyen** [comment]
If you're saying `defaultProps` to Flex, instead of putting the fallback `color` values into the theme, that seems like an arbitrary distinction and kind of fragile given the rest of the styles are in the theme, and what happens if we add more functions in the future, we're going to need to refactor all other components that set those styles in the theme?

**Comment by jxnblk** [comment]
Not sure I 100% follow what problem you're running into, but I suspect it *might* have to do with conflating `props` and style objects. The styled-system `color` function adds the styled-system `color` and `bg` *props* to the component. The `themeGet` utility gets a value from the theme, in your example it's getting `theme.Flex` and passing it to styled-components which is interpreting it as a style object, not a prop. The `color` prop just happens to be named consistently with the CSS property `color`. Since you've passed `themeGet('Flex')` to the styled-component after the styled-system `color` function, styled-components will always use `Flex: { color: 'blue' }` for the Flex component. Generally I'd suggest using either styled-system props *or* hard-coded style values, but not mixing them together, since you can easily run into CSS source order issues like this
