### ISSUE TITLE
Semantic Release?

### ISSUE THREAD

**Issue by StevenLangbroek** [jxnblk/styled-system#357]
I've been working with [`semantic-release`](https://semantic-release.gitbook.io/semantic-release/) for our "internal open-source" at Quandoo, and I've really come to like how much hassle it takes out of releasing. Would you be interested in collaborating on implementing it?

**Comment by jxnblk** [comment]
Personally, I'm not a huge fan of the current breed of automatic versioning/release tools like this. In order to work well, it requires a lot of discipline with commit messages (including those of outside contributors) and isn't as intentional as I think handling releases should be. And with tools like npm, I don't really feel like releasing is much of a hassle for me

**Comment by StevenLangbroek** [comment]
I definitely see that, which is why we provide `git-cz` for authoring and `commitlint` for validation. All that being said, it is your project of course, and a perfectly valid opinion, so I'll leave it as is.

If you want to reevaluate at some point, I'd love to help (including writing contributor documentation).

**Comment by jxnblk** [comment]
Wow! Just now noticed I never added a CONTRIBUTING.md – I'd definitely be open for some help there – maybe with a CoC as well

**Comment by StevenLangbroek** [comment]
On it :)

**Comment by StevenLangbroek** [comment]
@jxnblk hey is there somewhere I can reach you privately? I have some questions I'd rather not jump you with without explaining my intentions and reasoning :).

**Comment by StevenLangbroek** [comment]
@jxnblk hello?
