### ISSUE TITLE
Spacing: String values integer like are not interpreted as raw values

### ISSUE THREAD

**Issue by lbineau** [jxnblk/styled-system#370]
According to the [spacing documentation](https://github.com/jxnblk/styled-system/blob/master/docs/api.md#space) String values are passed as raw CSS values.
```javascript
space: [4, 8, 16, 32, 64, 128, 256]
```
- Observed behavior
```html
p="0" // outputs padding: 4px
```
- Expected behavior
```html
p="0" // outputs padding: 0 (only p={0} should output padding: 4px)
```
Isolated code that reproduce the issue: https://codesandbox.io/s/6v3rqp088k

**Comment by jxnblk** [comment]
This is expected behavior and this happens because `space['0']` is picking up from the scale. The language in the docs is meant to be a simple way to explain how it works. Generally I'd recommend keeping the value `0` in the `space` array so that `0` always equals `0`, but passing `'0px'` to the prop will work with the array you've listed above
