### ISSUE TITLE
height does not exist

### ISSUE THREAD

**Issue by philholden** [jxnblk/styled-system#46]
height is in the docs but not in the code

**Comment by jxnblk** [comment]
Can you provide a link to where “height is in the docs”? There shouldn’t be a height function as it’s generally not a good css property to use often

**Comment by Kikobeats** [comment]
This happened to me the other day. Have sense do not include `height`.

You expected `height` because` width` is present, but the reality is you only use `height` for fixed things, like cards, input, etc. There is no customization here, just a fixed.

so include it as HoC make impossible determinate a generic user case for use it.

**Comment by DylanVann** [comment]
I have a hero image where the height should be responsive so I'd like to use an array.

Why is height not a good CSS property to use?

**Comment by DylanVann** [comment]
Anyways it seems to be included now but it doesn't seem to work responsively.

**Comment by xuopled** [comment]
It used in the doc [here](https://github.com/jxnblk/styled-system/blob/master/docs/api.md#layout) but does not seems to work
