### ISSUE TITLE
Getting array theme values using theme func

### ISSUE THREAD

**Issue by Jayphen** [jxnblk/styled-system#74]
The docs show an example of getting at a value [from the theme](https://github.com/jxnblk/styled-system#theme). How can I get at a value if it is part of an array? (space values for example).

**Comment by corygibbons** [comment]
@Jayphen You can use a number representing the index, so for example `theme('space.2')` would get the 3rd item in the `theme.space` array.

**Comment by Jayphen** [comment]
Thanks, that works.

**Comment by gregoralbrecht** [comment]
Quick question regarding this. I'd love to mainly use the [theme getter function](https://github.com/jxnblk/styled-system#theme). Reading the docs, I was under the impression that it would convert the values in the arrays—e.g. the font size scale— to `px`, just like the [fontSize utility](https://github.com/jxnblk/styled-system#fontsize-responsive). However, this does not work:

```
theme.js
------
const fontSizes = [12, 14, 16, 20, 24, 32, 48, 64, 72]
export default { fontSizes }
```

```
Component.js // doesn't work
------
export default styled.p`
    font-size: ${theme('fontSizes.1')};
`
```

If I add `px` manually (see below), it works. Is that intentional or did I miss something?
```
Component.js // works
------
export default styled.p`
    font-size: ${theme('fontSizes.1')}px;
`
```

**Comment by alanbsmith** [comment]
@gregoralbrecht,

I think that issue has to do with your browser requiring a unit of measure for the font-size property. It needs to know whether you want `rem`, `em`, `px`, etc.

If you updated your array to look like this:
```js
['12px', '14px', '16px', '20px', '24px', '32px', '48px', '64px', '72px']
```

You could use `font-size: ${theme('fontSizes.1')};`

**Comment by gregoralbrecht** [comment]
@alanbsmith Thanks for the response! I'm aware we need a unit measure here, just trying to figure out how to best use this library. In the documentation the font size scales are provided as:

```
// typographic scale
const fontSizes = [
  12, 14, 16, 20, 24, 32, 48, 64, 96, 128
]
```

And about the `fontSize` utility it also says: _"Numbers from 0-8 (or theme.fontSizes.length) are converted to values on the font size scale."_

Personally, I would have loved to use the [theme function](https://github.com/jxnblk/styled-system#theme) exclusively because I don't end up with a ton of props on each component. So I'm just trying to understand how to properly define my (responsive) scales :)

**Comment by jxnblk** [comment]
If you're only wanting to use the theme values in styled-components without props, you can wrap the `themeGet` and `util.px` functions for your own use. Something like:

```js
import { themeGet, util } from 'styled-system'
const themePx = (...args) => props => util.px(themeGet(...args)(props))
```
