### ISSUE TITLE
Please rename prop-types to something else (please read)

### ISSUE THREAD

**Issue by zentuit** [jxnblk/styled-system#77]
I understand that this has come up before and it was dealt with in a PR.  However there is still and issue.  Webpack has a bug (that I'm trying to get tracked down) where the resolution graph gets messed up and results in `prop-types` trying to require itself.

Here's a gist of what I'm seeing: https://gist.github.com/zentuit/af24021fa3d95b340413587c4984432e

React's `prop-types` is moduleId 48 and styled-system's `prop-types` is moduleId 528. Instead of 
```
var _propTypes = __webpack_require__(48);
```
I'm getting
```
var _propTypes = __webpack_require__(528);
```

**Comment by jxnblk** [comment]
This typically is due to web pack's `resolve.modules` being incorrectly used with a non-absolute path – see https://github.com/jxnblk/grid-styled/issues/51#issuecomment-336116426

Regardless of what I rename the local module file in this library, the issue could come up with any npm package that shares the same name. Short of namespacing modules in this package, which should be unnecessary due to how modules work by default, there's not really a great way to avoid this sort of thing, and you should ensure that your application's module aliasing doesn't cause it to behave in non-standard ways.

Hope that helps and let me know if that doesn't resolve the issue.
